// Generated by CoffeeScript 1.3.1
(function() {
  var assets, config, cons, engine, express, flash, fs, handlbars, http, mongoose, passport, server, xmpp;

  fs = require('fs');

  http = require('http');

  express = require('express');

  cons = require('consolidate');

  config = require('yaml-config');

  handlbars = require('handlebars');

  engine = require('ejs-locals');

  passport = require('passport');

  assets = require('connect-assets');

  flash = require('connect-flash');

  xmpp = require('sticky-xmpp');

  GLOBAL.settings = config.readConfig('config/app.yaml');

  GLOBAL.app = module.exports = express.createServer();

  app.product_name = 'Sticky.io';

  app.env = process.env.NODE_ENV;

  app.root_dir = __dirname;

  app.configure(function() {
    var pub_dir;
    pub_dir = __dirname + '/public';
    app.use(assets({
      build: false,
      buildDir: 'public'
    }));
    app.engine('ejs', engine);
    app.set('views', __dirname + '/app/views');
    app.set('view engine', 'ejs');
    app.use(express["static"](pub_dir));
    app.use(express.favicon());
    app.use(express.logger('dev'));
    app.use(express.bodyParser());
    app.use(express.methodOverride());
    app.use(express.cookieParser('sc2ishard'));
    app.use(express.session({
      store: require('mongoose-session')
    }));
    app.use(passport.initialize());
    app.use(passport.session());
    app.use(flash());
    return app.use(app.router);
  });

  mongoose = require('./app/models');

  app.models = mongoose.models;

  require('./app/controllers');

  xmpp.start();

  server = app.listen(settings.port);

  console.log("Server running at http://" + settings.domain);

}).call(this);
