#!/bin/sh
 

echo `date +%s` > VERSION

git add .
git commit -m "deploying version num: `date +%s`"
git push origin master

deploy sticky01
deploy sticky02

sleep 15

echo '\033[01;32;5;160mwaiting for sticky to boot up...'

script/check-http-status sticky.io
